baseURL="https://nowhash.github.io"
languageCode="en"
defaultContentLanguage="en"
title="Nowhash'sDen"
preserveTaxonomyNames=true
enableRobotsTXT=true
enableEmoji=true
theme="even"
enableGitInfo=false

paginate=5

copyright="nowhash chy"

[author]
name="Abu Nowhash Chy"

[sitemap]
changefreq="weekly"
priority=0.5
filename="sitemap.xml"

[[menu.main]]
name="Home"
weight=10
identifier="home"
url="/"
[[menu.main]]
name="Blog"
weight=20
identifier="blog"
url="/blog/"
[[menu.main]]
name="Archives"
weight=30
identifier="archives"
url="/post/"

[params]
version="4.x"
debug=false

since="2021"
gitRepo="nowhash"

logoTitle="nowhash'sden"
keywords=["Technology","Poetry","Blog","Literature","Programming","Machine Learning","ML"]
description=""

archivePaginate=10

showArchiveCount=false

dateFormatToUse="2006-01-02"

moreMeta=false

highlightInClient=false

toc=true
autoCollapseToc=false
fancybox=true

postMetaInFooter=true
linkToMarkDown=false
contentCopyright=''#e.g.'<arel="licensenoopener"href="https://creativecommons.org/licenses/by-nc-nd/4.0/"target="_blank">CCBY-NC-ND4.0</a>'

customCSS=[]
customJS=[]

uglyURLs=false

showLanguageSelector=false

[params.social]
d-facebook="https://www.facebook.com/nowhashchy"
e-linkedin="https://www.linkedin.com/in/nowhashchy"
g-github="https://github.com/nowhash"

